config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'base#index'
    resources :projects, only: [:new, :create, :destroy]
    resources :users

    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  devise_for :users
  root "projects#index"
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :tickets do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :tickets, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :assets, only: [:show, :new], path: :files do
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  skip_after_action :verify_authorized, :verify_policy_scoped
  before_action :authorize_admin!

  def index
  end
end

private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
  def roles
    hash = {}
    ['manager', 'editor', 'viewer'].each do |role|
      hash[role.titleize] = role
    end
    hash
  end
end
  

app/views/admin/base/index.html.erb
<div class="row">
  <div class="col-md-9">
    <header>
      <h1>Admin Lounge</h1>
    </header>

    <p>Welcome to Ticketee's Admin Lounge. Please enjoy your stay.</p>
  </div>

<div class="col-md-3">
  <h2>Admin Links</h2>
  <ul class="nav nav-stacked">
    <li><%= link_to "Users", admin_users_path %></li>
    <li><%= link_to "States", admin_states_path %></li>
  </ul>
</div>